### ISSUE TITLE
xposed update

### ISSUE THREAD

**Issue by xumxum** [pR0Ps/Entrust-IdentityGuard-Unblocker#2]
Hey great app to remove this annoying limitation...
Can we please also get an update through xposed for version 1.1?

**Comment by pR0Ps** [comment]
For sure, it hasn't happened yet only because I don't have access to the computer that has the signing key at the moment.

I should be able to release v1.1 to the Xposed repo in about a week.

**Comment by pR0Ps** [comment]
Update has been pushed to the Xposed Module Repo. Please create a new issue if you find any problems with v1.1.

**Comment by xumxum** [comment]
update works great, many thanks :)
