### ISSUE TITLE
It give the dame error of unsecured devices

### ISSUE THREAD

**Issue by chukyz** [pR0Ps/Entrust-IdentityGuard-Unblocker#3]
I hace xposed and i instaló this module in y moto g2 but when i open the entrusted app gives: mutual activation is not compatible with an unsafe device. The versión that i hace is 3.1.0.32 and xpose in versión 4 alpha4. Thanks. Android versión 5.0.2

**Comment by pR0Ps** [comment]
Dupe of #2, update will be out soon
