### ISSUE TITLE
entrust 3.2

### ISSUE THREAD

**Issue by eaglespeed** [pR0Ps/Entrust-IdentityGuard-Unblocker#5]
hi. 
the app updated to 3.2 and the module no longer works on it. it went back to saying it's unsecure device. 
Thank you for your work.

**Comment by pR0Ps** [comment]
Duplicate of #4 . It's been fixed in the code, I'm currently just waiting for F-Droid to build it so I can update the APK in the module repository.

**Comment by eaglespeed** [comment]
thank you very much, I really appreciate how dedicated you are to this and how you reply fast, despite not getting any compensation. I wish u the best, I had to redo the activation on entrust desktop since I couldn't delay work interactions.
